### PR TITLE
Drop i386 arch

### PR DESCRIPTION
**Pull request by Inglebard**
- Drop i386 arch
- add release version to metainfo

### CODE REVIEW

**Comment by Inglebard** [comment]
Use it right now. At least no issue. Don't know why it failed earlier.

**Comment by wjt** [comment]
Thanks! If you actively use Anydesk, do you have any interest in adopting this app? (I don't, I inherited it from former colleagues who submitted it.)

**Comment by Inglebard** [comment]
Same answer : https://github.com/flathub/com.anydesk.Anydesk/issues/13#issuecomment-733029709 :smile:

**Comment by wjt** [comment]
:grinning:

**Comment by Inglebard** [comment]
The 6.1.0 flathub package doesn't seems to be available right.
Is there another file to change ?

**Comment by wjt** [comment]
By default there is a few hours' delay until a new build gets published. I pressed the "publish" button

**Comment by Inglebard** [comment]
Sorry to bother you again but after the update, "flatpak list" still show version 6.0.1. I don't see the file to change to 6.1.0.

**Comment by wjt** [comment]
Fixed in eb4fd12.

**Comment by Inglebard** [comment]
My bad. Thanks

**Pull request merged**
