### PR TITLE
Update runtime and pciutils

### PR DESCRIPTION
**Pull request by paolostivanin**
* update runtime to 21.08
* update pciutils to 3.7.0

Tested locally, works fine.

### CODE REVIEW

**Comment by wjt** [comment]
Thanks!

Do you actually use Anydesk? Would you be interested in adopting this Flatpak?

**Comment by paolostivanin** [comment]
Hello! Yes, I use Anydesk when I need to perform remote desktop management.
I'll gladly adopt this package :)

**Comment by wjt** [comment]
@flathub/admins Please could you add @paolostivanin to the maintainers for this project?

**Comment by barthalion** [comment]
Invitation has been sent!

**Comment by paolostivanin** [comment]
Thanks :)

**Pull request merged**
